fix Service.php validation empty error message bug
Sevavietl/TNTExpressConnect pull request #1
Opened 2018-06-06 12:31 UTC by mishavetl

2018-06-06 12:43 UTC, Sevavietl commented on src/Ship/Service.php
> +		$response = $this->sendRequest($this->serializer->serialize($xml));
Padding problem here and so on. Please, fix styles.

2018-06-06 12:44 UTC, Sevavietl requested changes
Please, fix code style problems

2018-06-06 13:05 UTC, mishavetl commented
It is fixed now. The problem was about mixed up tabs and spaces.

2018-06-06 13:17 UTC, Sevavietl commented
@mishavetl, please squash all commits into one.

2018-06-06 17:04 UTC, mishavetl commented
All done.

2018-06-07 11:05 UTC, merged

2018-06-07 11:05 UTC, Sevavietl commented
@mishavetl, thanks for the PR